AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda CVE filter parser 

Parameters:
  KMSKEY:
    Type: String
    Description: My SomeVar
    Default: default value
  BUCKET:
    Type: String
    Description: My SomeVar
    Default: default value

Resources:
  filter:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7 
      Timeout: 60
      Environment:
        Variables:
          KMSKEY: !Ref KMSKEY
          BUCKET: !Ref BUCKET
